backend/mysite/mysite/appointments/urls.py
from django.urls import path
from . import views

app_name = 'appointments'

urlpatterns = [
    path('',views.index, name = 'index'),
    path('PatientLoginPage/',views.PatientLoginPage,name = 'PatientLoginPage'),# check patient in datebase
    path('PatientLogin/',views.PatientLogin,name = 'PatientLogin'), #send html page
    path('CreatePatient/', views.CreatePatient, name = 'CreatePatient'),
    path('PatientUpdate/', views.PatientUpdate, name='PatientUpdate'),
    path('CreateAppointment/', views.CreateAppointment, name='CreateAppointment'),
    path('DoctorRegistration/', views.DoctorRegistration, name='DoctorRegistration'),
    path('ShowPatientInfo/', views.ShowPatientInfo, name='ShowPatientInfo'),


]

backend/mysite/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appointments.urls'))
]

backend/mysite/mysite/appointments/models.py
from django.db import models

# Create your models here.
class Patient(models.Model):
    surname = models.CharField(max_length=20)
    name = models.CharField(max_length=20)
    patronymic= models.CharField(max_length=20)
    sex = models.CharField(max_length=20)
    birth = models.CharField(max_length=10)
    login = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    telephone_number = models.CharField(max_length=12)
    def __str__(self):
        return self.name

class Doctor(models.Model):
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)
    speciality = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Appointments(models.Model):
    date = models.CharField(max_length=20)
    time = models.CharField(max_length=20)
    doctor = models.ForeignKey(Doctor,on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient,on_delete=models.CASCADE)
    info = models.TextField()

    def __str__(self):
        return self.name

backend/mysite/mysite/appointments/forms.py
from django import forms
from appointments.models import Appointments, Doctor, Patient

class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointments
        fields = ['date', 'time','doctor', 'patient', 'info']


class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = ['name', 'surname', 'speciality']



class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['surname','name','patronymic','sex','birth', 'login','password','telephone_number']

class PatInfoForm(forms.Form):
    name = forms.IntegerField()

backend/mysite/mysite/appointments/views.py
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
from appointments.models import Patient
from appointments.models import Appointments
from appointments.models import Doctor
from .forms import AppointmentForm, DoctorForm, PatientForm, PatInfoForm
from django.core import serializers



def index(request):
    return render(request, 'appointments/index.html')


def PatientLoginPage(request):
    patient_login = request.POST['PatientLogin']
    patient_pswrd = request.POST['PatientPassword']
    try:
        Patient_obj = Patient.objects.get(login=patient_login, password=patient_pswrd)
    except:
        return JsonResponse({'status': 'failed'})
    return JsonResponse({'status': 'successful'})


def PatientLogin(request):
    return render(request, 'appointments/patient_login.html')


def CreatePatient(request):
    if request.method == "POST":
        try:
            login = request.POST['login']
            password = request.POST['password']
            name = request.POST['name']
            surname = request.POST['surname']
            patronymic = request.POST['patronymic']
            birth = request.POST['birth']
            sex = request.POST['sex']
            telephone_number = request.POST['telephone_number']
            newPatient = Patient(surname=surname, name=name, patronymic=patronymic, sex=sex, birth=birth, login=login,
                                 password=password, telephone_number=telephone_number)
            newPatient.save()
            return JsonResponse({'status': 'successful'})
        except:
            return JsonResponse({'status': 'failed'})
    else:
        patient_form = PatientForm()
        return render(request, 'appointments/patient_register.html', {'form': patient_form})


def CreateAppointment(request):
    if request.method == "POST":
        try:
            appointment_form = AppointmentForm(request.POST)
            new_app = appointment_form.save()
            return JsonResponse({'status': 'successful'})
        except:
            return JsonResponse({'status': 'failed'})

    else:
        appointment_form = AppointmentForm()
        return render(request, 'appointments/create_appointment.html', {'form': appointment_form})


def DoctorRegistration(request):
    if request.method == "POST":
        try:
            name = request.POST.get("name")
            speciality = request.POST.get("speciality")
            surname = request.POST.get("surname")
            newDoctor = Doctor(name=name, surname=surname, speciality=speciality)
            newDoctor.save()
            return JsonResponse({'status': 'successfully'})
        except:
            return JsonResponse({'status': 'failed'})

    else:
        doctor_form = DoctorForm()
        return render(request, 'appointments/doctor_register.html', {'form': doctor_form})

def PatientUpdate(request):
    try:
        login = request.POST['login']
        password = request.POST['password']
        name = request.POST['name']
        surname = request.POST['surname']
        patronymic = request.POST['patronymic']
        birth = request.POST['birth']
        sex = request.POST['sex']
        telephone_number = request.POST['telephone_number']
        # update_patient = Patient.objects.get(id = id )
        newPatient = Patient(surname=surname, name=name, patronymic=patronymic, sex=sex, birth=birth, login=login,
                             password=password, telephone_number=telephone_number)
        newPatient.save()
        return JsonResponse({'status': 'successful'})
    except:
        return JsonResponse({'status': 'failed'})




    data = serializers.serialize("json", patInfo)


def ShowPatientInfo(request):
    if request.method == "POST":
        patient  = request.POST.get("name")
        patInfo = Patient.objects.get(id=patient)
        # data = serializers.serialize("json", patInfo)
        data={"surname":patInfo.surname,"name":patInfo.name,"birth":patInfo.birth}
        return render(request, 'appointments/patient_page.html',context=data)
    else:
        patChoice = PatInfoForm()
        return render(request, 'appointments/patient_page.html',{"form":patChoice})

backend/mysite/mysite/appointments/templates/appointments/create_appointment.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Django Forms</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="Send" >
</form>
</body>
</html>

backend/mysite/mysite/appointments/templates/appointments/doctor_register.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Django Forms</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="Send" >
</form>
</body>
</html>

backend/mysite/mysite/appointments/templates/appointments/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>AlphaHealth Home</title>
</head>
<body>

    <h1>Welcome To ApointmentApp</h1>

    <br/>
    <br/>

    <h3>Options</h3>

    <form action="/PatientLogin" method="get">
        <button type = "submit" value="Submit">PatientLogin</button>
    </form> <br/>

    <form action="/CreatePatient" method="get">
        <button type = "submit" value="Submit">CreatePatient</button>
    </form> <br/>
    <form action="/CreateAppointment" method="get">
        <button type = "submit" value="Submit">CreateAppointment</button>
    </form> <br/>
    <form action="/DoctorRegistration" method="get">
        <button type = "submit" value="Submit">DoctorRegistration</button>
    </form> <br/>
    <form action="/ShowPatientInfo" method="get">
        <button type = "submit" value="Submit">ShowPatientInfo</button>
    </form> <br/>

    <br/>


</body>
</html>

backend/mysite/mysite/appointments/templates/appointments/patient_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>Patient Login</title>
</head>
<body>

    <h1>Please enter you credentials or create an account</h1>

    <br/>
    <br/>

    <h3>LOGIN : </h3>


    <form action="/PatientLoginPage/" method="POST">
        {% csrf_token %}
        <h4>Login : </h4> <input type="text"  id="PatientLogin" name = "PatientLogin" required>
        <br/>
        <h4>Password : </h4> <input type="password"  id="PatientPassword" name = "PatientPassword" required>
        <br/>
        <button type = "submit" value="Submit" id = "PatientLoginButton">LOGIN!</button>
    </form>




    <p><i>If you are a new user, create an account</i></p>

    <form action="/CreatePatient/" method="get">
        <button type = "submit" value="Submit">Create Account</button>
    </form>



</body>
</html>

backend/mysite/mysite/appointments/templates/appointments/patient_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Patien page </title>
</head>
<body>

 <form method="POST">
        {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="Send" >
<br>
<h1> Recent Appointment</h1>
Date :
<br>
Time :
<br>
Specialist :
<br>


Photo !TODO!
<br>
Surname : {{surname}}
<br>
Name: {{name}}
<br>
Birthday: {{birth}}
<br>




</body>
</html>

backend/mysite/mysite/appointments/templates/appointments/patient_register.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Django Forms</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="Send" >
</form>
  <a href = "{% url 'appointments:PatientLogin'%}">Login page</a>
</body>
</html>